### ISSUE TITLE
Multiple memory consumption when changing the window size.

### ISSUE THREAD

**Issue by KaxelDreamhack123** [SaschaWillems/VulkanInfiniteProceduralTerrain#3]
If you run the project and look in the Memory window with the Heap Usage characteristic, then if you change the window (say to full screen), the heap Usage will increase, but if you return the window size to the first state, it will increase again. If you do this several times , then in VulkanExampleBase.cpp at line 2154, a crash will trigger on 

`VK_CHECK_RESULT(vkAllocateMemory(device, &memAllocInfo, nullptr, &multisampleTarget.depth.memory));`

To be honest, I don't know how to deal with this problem at all. If you change the size of the window using the buttons, then memory clogging is slower than if you set the window size with the mouse, rotate it, etc., then it is 4 times faster.

**Comment by SaschaWillems** [comment]
Please take note of this on top of the readme of this repo:

"This is a personal playground for an infinite procedurally generated terrain renderer in Vulkan. No guarantee that the code will work."

**Comment by KaxelDreamhack123** [comment]
> Please take note of this on top of the readme of this repo:
> 
> "This is a personal playground for an infinite procedurally generated terrain renderer in Vulkan. No guarantee that the code will work."

I understand that, I just wanted to know what you think about it. I am very interested in studying this project and I want to know your opinion, maybe you know how to fix it.

**Comment by KaxelDreamhack123** [comment]
This can be considered as a question that could be asked in the Discord Vulkan server, but I thought it was better here, because there is a lot of related code here and it seems to me too much to send it all. I don't know how you'll take it.

**Comment by SaschaWillems** [comment]
Well, my last public commit to this project was two years ago, so I simply can't answer that.

**Comment by KaxelDreamhack123** [comment]
> Well, my last public commit to this project was two years ago, so I simply can't answer that.

Well, in general, it would be pointless to ask questions here, I suppose?

**Comment by SaschaWillems** [comment]
Mostly yes.

**Comment by KaxelDreamhack123** [comment]
> Mostly y

Understood, accepted, secured.
